apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ngdeploy
spec:
  description: argo projects to create  
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
  destinations:
    - namespace: ngdeploy
      server: https://34.79.0.21
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/vettom/ArgoCD.git
