{{- if and .Values.prometheus_stack.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
     release: kube-prometheus-stack
  name: cert-manager-alerts
  namespace: monitoring
spec:
  groups:
    - name: cert-manager
      rules:
        - alert: CertManagerAbsent
          annotations:
            summary: "Cert Manager has dissapeared from Prometheus service discovery."
          expr: |
            absent(up{service="cert-manager"})
          for: 10m
          labels:
            team: cloudops
            service: certmanager
            severity: warning
        - alert: CertManagerCertExpirySoon
          annotations:
            summary: "The cert  {{`{{$labels.name}}`}} is  {{`{{$value | humanizeDuration }}`}} from expiry, it should have renewed over a week ago."
            runbook_url: https://baueraudio.atlassian.net/wiki/spaces/Rayo/pages/284033025/Quick+Links+and+shortcuts
          expr: |
            avg by (namespace, name) (certmanager_certificate_expiration_timestamp_seconds - time())  < (21 * 24 * 3600) > 0
          for: 10m
          labels:
            team: cloudops
            service: certmanager
            severity: warning
        - alert: CertManagerCertFailedRenewal
          annotations:
            summary: "The cert  {{`{{ $labels.name }}`}} is  {{`{{ $value | humanizeDuration }}`}} from expiry, it should have renewed by now."
            runbook_url: https://baueraudio.atlassian.net/wiki/spaces/Rayo/pages/284033025/Quick+Links+and+shortcuts
          expr: |
            avg by (namespace, name) (certmanager_certificate_expiration_timestamp_seconds - time())  < (10 * 24 * 3600) > 0
          for: 10m
          labels:
            team: cloudops
            service: certmanager
            severity: warning
        - alert: CertManagerCertNotReady
          annotations:
            summary: "The cert  {{`{{`}} $labels.name {{`}}`}} is not ready to serve traffic."
            runbook_url: https://baueraudio.atlassian.net/wiki/spaces/Rayo/pages/284033025/Quick+Links+and+shortcuts
          expr: |
            max by (name, exported_namespace, namespace, condition) ( certmanager_certificate_ready_status{condition!="True"} == 1)
          for: 10m
          labels:
            team: cloudops
            service: certmanager
            severity: warning
        - alert: CertManagerHittingRateLimits
          annotations:
            summary: "Cert manager hitting LetsEncrypt rate limits. Check for certificate failures"
            runbook_url: https://baueraudio.atlassian.net/wiki/spaces/Rayo/pages/284033025/Quick+Links+and+shortcuts
          expr: |
            sum by (host) (rate(certmanager_http_acme_client_request_count{status="429"}[5m]))
          for: 10m
          labels:
            team: cloudops
            service: certmanager
            severity: critical
{{- end -}}