{{- if and .Values.prometheus_stack.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
     release: kube-prometheus-stack
  name: lb-controller-alerts
  namespace: monitoring
spec:
  groups:
    - name: lb-controller
      rules:
        - alert: LBCertificateErrors
          annotations:
            summary: "LoadBalancer controller is reporting certificate error on pod {{`{{$labels.pod }}`}} in {{`{{$labels.namespace}}`}}."
            runbook_url: https://baueraudio.atlassian.net/wiki/spaces/Rayo/pages/284033025/Quick+Links+and+shortcuts
          expr: |
            sum by (namespace,pod) (certwatcher_read_certificate_errors_total) > 1
          for: 10m
          labels:
            team: cloudops
            severity: warning
{{- end -}}