{{- if and .Values.prometheus_stack.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
     release: kube-prometheus-stack
  name: gatewayapi-alerts
  namespace: monitoring
spec:
  groups:
    - name: gatewayapi
      rules:
        - alert: gatewayApiErrors
          annotations:
            summary: "Gateway API is reporting reconcile error."
          expr: |
            controller_runtime_reconcile_errors_total{controller="gatewayapi"} != 0
          for: 10m
          labels:
            team: cloudops
            service: gatewayapi
            severity: warning
    - name: gatewayhealth
      rules:
        - alert: gatewayHelthyMembers
          annotations:
            summary: "Gateway is reporting unhealthy cluster members."
          expr: |
            sum by(namespace) (envoy_cluster_membership_total{namespace="gateway"}) - sum by(namespace) (envoy_cluster_membership_healthy{namespace="gateway"}) != 0
          for: 10m
          labels:
            team: cloudops
            service: gatewayapi
            severity: warning
{{- end -}}     