{{- if and .Values.prometheus_stack.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
     release: kube-prometheus-stack
  name: external-secrets-alerts
  namespace: monitoring
spec:
  groups:
    - name: external-secrets
      rules:
        - alert: ExternalSecretsSyncErrors
          annotations:
            summary: "There are sync errors in external secrets"
            runbook_url: https://baueraudio.atlassian.net/wiki/spaces/Rayo/pages/284033025/Quick+Links+and+shortcuts
          expr: |
            irate(externalsecret_sync_calls_error[5m]) > 0
          for: 10m
          labels:
            team: cloudops
            service: externalsecrets
            severity: warning
        - alert: ExternalSecretsBadStatus
          annotations:
            summary: "There are status errors in external secrets"
            runbook_url: https://baueraudio.atlassian.net/wiki/spaces/Rayo/pages/284033025/Quick+Links+and+shortcuts
          expr: |
            externalsecret_status_condition{condition="Ready",status="False"} == 1
          for: 10m
          labels:
            team: cloudops
            service: externalsecrets
            severity: warning
{{- end -}}