apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-chart
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: public.ecr.aws/aws-controllers-k8s
      chart: iam-chart
      targetRevision: 1.1.0
      helm:
        valuesObject:
          aws:
            region: eu-west-1
