apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.8.4
    helm:
      valuesObject:
        server:
          extraArgs:
            - --insecure
        configs:
          params:
            application.namespaces: "default, argocd, dvdemo"
            applicationsetcontroller.namespaces: "default, argocd, dvdemo"
            notificationscontroller.selfservice.enabled: true
            applicationsetcontroller.allowed.scm.providers: false
          cm:
            application.resourceTrackingMethod: annotation+label
        notifications:
          secret:
            create: false
          cm:
            # -- Whether helm chart creates notifications controller config map
            create: true
