apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  description: Project for Core Applications
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://argoproj.github.io/argo-helm
    - https://charts.jetstack.io
    - https://aws.github.io/eks-charts
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    - https://aws.github.io/secrets-store-csi-driver-provider-aws
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/external-dns
    - https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    - https://github.com/BauerXcel/uk-audio-services-core-apps
    - https://github.com/BauerXcel/uk-audio-services-eks-bootstrap
    - https://helm.linkerd.io/stable
    - https://charts.karpenter.sh
    - https://prometheus-community.github.io/helm-charts
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://kubernetes.github.io/ingress-nginx
    - public.ecr.aws/karpenter
    - ghcr.io/bauerxcel
    - docker.io/envoyproxy
    - https://charts.wiz.io/
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  description: Project for generic Applications
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - ghcr.io/bauerxcel
    - 800508964711.dkr.ecr.eu-west-2.amazonaws.com/bauerxcel
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
