apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
spec:
  destination:
    namespace: wordpress
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/wordpress
    repoURL: 'https://github.com/vettom/ArgoCD.git'
    targetRevision: HEAD
  project: wordpress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
